version: "3.8"

services:
  backend:
    image: darrengun15/todolist-backend:latest
    pull_policy: always
    container_name: todolist-backend
    restart: always
    environment:
      PORT: ${PORT}
      CONNECTION_URL: ${CONNECTION_URL}
      CLIENT_URL: ${CLIENT_URL}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    ports:
      - "3042:3042"
    networks:
      - csbiweb-tunnel

  frontend:
    image: darrengun15/todolist-frontend:latest
    pull_policy: always
    container_name: todolist-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3041:3041"
    networks:
      - csbiweb-tunnel

volumes:
  mongodb_data:

networks:
  csbiweb-tunnel:
    external: true